// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEm0U_Kqs-t3Rg_1TedQW13wWbgR8a2oI',
    appId: '1:342633498862:web:b1d35af11a3e38220a4bff',
    messagingSenderId: '342633498862',
    projectId: 'smadrasha-e55c8',
    authDomain: 'smadrasha-e55c8.firebaseapp.com',
    storageBucket: 'smadrasha-e55c8.firebasestorage.app',
    measurementId: 'G-Y1S1KSD20Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZMn5U1mViofMQAUscTU7HTxxSczrtg48',
    appId: '1:342633498862:android:1e59421e5914d81c0a4bff',
    messagingSenderId: '342633498862',
    projectId: 'smadrasha-e55c8',
    storageBucket: 'smadrasha-e55c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMWBXcY7bWFEtAxno7r9uS7SjuLBfOWQ',
    appId: '1:342633498862:ios:9bfda84171de12b60a4bff',
    messagingSenderId: '342633498862',
    projectId: 'smadrasha-e55c8',
    storageBucket: 'smadrasha-e55c8.firebasestorage.app',
    iosClientId: '342633498862-am8c8g9cindrpe8jv5b772iki8vpo9ko.apps.googleusercontent.com',
    iosBundleId: 'com.smadrasha.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfMWBXcY7bWFEtAxno7r9uS7SjuLBfOWQ',
    appId: '1:342633498862:ios:3b3a436172100b320a4bff',
    messagingSenderId: '342633498862',
    projectId: 'smadrasha-e55c8',
    storageBucket: 'smadrasha-e55c8.firebasestorage.app',
    iosClientId: '342633498862-frrq88hm9m0ja3a3dtken198mn6bb6kc.apps.googleusercontent.com',
    iosBundleId: 'com.smadrasha.app.smadrasha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEm0U_Kqs-t3Rg_1TedQW13wWbgR8a2oI',
    appId: '1:342633498862:web:66bc20579c8938d60a4bff',
    messagingSenderId: '342633498862',
    projectId: 'smadrasha-e55c8',
    authDomain: 'smadrasha-e55c8.firebaseapp.com',
    storageBucket: 'smadrasha-e55c8.firebasestorage.app',
    measurementId: 'G-Q2HT4H7GZP',
  );
}
